### ISSUE TITLE
Failing to compile specific CSS-Rule

### ISSUE THREAD

**Issue by MrAvantiC** [luisrudge/postcss-flexbugs-fixes#68] opened 2020-04-27 06:34 UTC
Hello there,
I recently stumbled into an issue when using Next.js - which utilizes *postcss* - when trying to compile this specific line of CSS:
`flex: 1 0 calc(30% - (30px / 3));`

After opening an issue over there (https://github.com/zeit/next.js/issues/12207#issue-606963957) one of the maintainers pinpointed the problem being an empty `postcss-loader` loader config, which causes the above error.
Find his response here: https://github.com/zeit/next.js/issues/12207#issuecomment-619649854

You can find an example repository in the initial post of the original issue, but if I can provide anything to help resolve this issue, let me know.

Kind regards.

**Comment by mattcarlotta** [comment] 2020-04-27 06:41
Just to clarify, the problem isn't an empty config, but a `postcss-loader` config that utilizes this package and tries to compile the above CSS. In particular, the package tries to compile:

`flex: 1 0 calc(30% - (30px / 3));` 
to
`flex: 1 0 calc(30% - (30px / 3);` by leaving off the inner parenthesis which converts it into invalid CSS.

**Comment by luisrudge** [comment] 2020-04-27 20:55
fixed in postcss-flexbugs-fixes@4.2.1

**Closed** 2020-04-27 20:54 UTC

**Comment by MrAvantiC** [comment] 2020-04-28 07:22
Thank you!

**Comment by ebs-PriyankaKanwar** [comment] 2020-05-04 11:17
Hello Team
I have facing issues regarding the next-CSS . I have using next-CSS but they are giving me a warning and when I removed the next-CSS from next.config file. my style CSS has not loaded chunks in the production. and my CSS is out of order in a production build.
Can you plz help me.
